[build]
  base = "vtt-react"
  command = "rm -rf node_modules && rm -rf build && rm -rf .cache && npm ci --force && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"
  # Enable build optimizations
  CI = "true"
  # Increase memory for build process
  NODE_OPTIONS = "--max-old-space-size=8192"
  # Enable production optimizations
  REACT_APP_BUILD_MODE = "production"
  REACT_APP_ENV = "production"
  # Optimize bundle size
  INLINE_RUNTIME_CHUNK = "false"
  # Browser compatibility
  BROWSERSLIST_ENV = "production"
  # Multiplayer Server Configuration
  REACT_APP_SOCKET_URL = "https://descension-production.up.railway.app"
  # Firebase Configuration
  REACT_APP_FIREBASE_API_KEY = "AIzaSyDs9SSWy1J_aSX3LvHUBbI9fwi68cuaX7A"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "mythrill-ff7c6.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "mythrill-ff7c6"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "mythrill-ff7c6.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "715658408409"
  REACT_APP_FIREBASE_APP_ID = "1:715658408409:web:3a926eba858e529d66a9c8"
  REACT_APP_FIREBASE_MEASUREMENT_ID = "G-WL4DX5LRYX"
  # Force fresh build
  BUILD_TIMESTAMP = "2025-01-30-weapon-handedness-fixes"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Enable CORS for drag and drop functionality
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
