[build]
  base = "vtt-react"
  publish = "build"
  command = "npm ci && npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"
  CI = "true"
  NODE_OPTIONS = "--max-old-space-size=8192"
  REACT_APP_BUILD_MODE = "production"
  REACT_APP_ENV = "production"
  INLINE_RUNTIME_CHUNK = "false"
  BROWSERSLIST_ENV = "production"
  REACT_APP_SOCKET_URL = "https://descension-mythrill.up.railway.app"
  REACT_APP_FIREBASE_API_KEY = "AIzaSyDs9SSWy1J_aSX3LvHUBbI9fwi68cuaX7A"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "mythrill-ff7c6.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "mythrill-ff7c6"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "mythrill-ff7c6.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "715658408409"
  REACT_APP_FIREBASE_APP_ID = "1:715658408409:web:3a926eba858e529d66a9c8"
  REACT_APP_FIREBASE_MEASUREMENT_ID = "G-WL4DX5LRYX"
  BUILD_TIMESTAMP = "2025-09-21-character-name-fix"

# Redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# All environment variables are configured above in [build.environment]
