[build]
builder = "nixpacks"

[deploy]
startCommand = "cd vtt-react && npm ci && npm run build && npx serve -s build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = {
  NODE_ENV = "production",
  GENERATE_SOURCEMAP = "false",
  CI = "true",
  NODE_OPTIONS = "--max-old-space-size=8192",
  REACT_APP_BUILD_MODE = "production",
  REACT_APP_ENV = "production",
  INLINE_RUNTIME_CHUNK = "false",
  BROWSERSLIST_ENV = "production",
  REACT_APP_SOCKET_URL = "https://descension-production.up.railway.app",
  REACT_APP_FIREBASE_API_KEY = "AIzaSyDs9SSWy1J_aSX3LvHUBbI9fwi68cuaX7A",
  REACT_APP_FIREBASE_AUTH_DOMAIN = "mythrill-ff7c6.firebaseapp.com",
  REACT_APP_FIREBASE_PROJECT_ID = "mythrill-ff7c6",
  REACT_APP_FIREBASE_STORAGE_BUCKET = "mythrill-ff7c6.firebasestorage.app",
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "715658408409",
  REACT_APP_FIREBASE_APP_ID = "1:715658408409:web:3a926eba858e529d66a9c8",
  REACT_APP_FIREBASE_MEASUREMENT_ID = "G-WL4DX5LRYX"
}
