// List of item icons from items folder categorized by type
export const WOW_ICONS = {
    weapons: {
        swords: [
            { id: 'Weapons/Swords/sword-basic-straight-beige-blade-brown-hilt', name: 'Basic Sword' },
            { id: 'Weapons/Swords/sword-basic-japanese-golden-guard-pommel', name: 'Ornate Sword' },
            { id: 'Weapons/Swords/sword-basic-serrated-tan-blade-brown-hilt', name: 'Bastard Sword' },
            { id: 'Weapons/Swords/sword-fire-molten-red-orange-yellow-curved-guard', name: 'Curved Blade' },
            { id: 'Weapons/Swords/sword-basic-straight-beige-blade-brown-diamond-guard', name: 'Broadsword' },
            { id: 'Weapons/Rapier/rapier-curved-blade-rusty-bronze-orange-brown-aged', name: 'Rapier' },
            { id: 'Weapons/Swords/sword-basic-serrated-tan-brown-simple', name: 'Longsword' },
        ],
        axes: [
            { id: 'Weapons/Axe/axe-brown-handle-beige-blade', name: 'Battle Axe' },
            { id: 'Weapons/Axe/double-bladed-axe-asymmetric-bronze', name: 'Double Axe' },
            { id: 'Weapons/Axe/axe-brown-handle-yellow-head', name: 'War Axe' },
            { id: 'Weapons/Throwing Axe/throwing-axe-brown-handle-beige-blade-standard', name: 'Throwing Axe' },
            { id: 'Weapons/Axe/axe-reddish-orange-gem', name: 'Heavy Axe' },
            { id: 'Weapons/Axe/fiery-axe-flame-blade', name: 'Ceremonial Axe' },
        ],
        maces: [
            { id: 'Weapons/Mace/mace-spiked-club-brown-tan-bands-metal-spikes', name: 'Simple Mace' },
            { id: 'Weapons/Mace/mace-fire-spiked-red-orange-yellow-glowing', name: 'Spiked Mace' },
            { id: 'Weapons/Warhammer/warhammer-brown-tan-striking-face-beige-arrow-indicator', name: 'War Hammer' },
            { id: 'Weapons/Mace/mace-fire-segmented-teal-red-orange-yellow-bands', name: 'Flanged Mace' },
            { id: 'Weapons/Warhammer/warhammer-mace-spiked-metallic-gray-brown', name: 'Maul' },
            { id: 'Weapons/Mace/mace-fire-key-red-orange-yellow-flame-head', name: 'Ornate Mace' },
        ],
        staves: [
            { id: 'Weapons/Staff/staff-wooden-golden-star-green-wrapping-red-pommel', name: 'Wooden Staff' },
            { id: 'Weapons/Staff/staff-magical-fire-flame-hilt-orange-yellow-white-tip', name: 'Magic Staff' },
            { id: 'Weapons/Staff/staff-magical-glowing-amber-segmented', name: 'Crystal Staff' },
            { id: 'Weapons/Staff/staff-golden-brown-y-pronged-trident-head', name: 'Gnarled Staff' },
            { id: 'Weapons/Staff/staff-magical-fire-sun-burst-eight-pointed-star', name: 'Ceremonial Staff' },
            { id: 'Weapons/Staff/staff-magical-fire-sun-burst-orange-yellow-white', name: 'Runed Staff' },
        ],
        bows: [
            { id: 'Weapons/Bows/bow-brown-limb-tips-recurve', name: 'Recurve Bow' },
            { id: 'Weapons/Bows/bow-simple-brown-tan-grip', name: 'Long Bow' },
            { id: 'Weapons/Bows/bow-nature-leaves-berry-decorative', name: 'Elven Bow' },
            { id: 'Weapons/Crossbow/crossbow-reddish-brown-loaded', name: 'Crossbow' },
            { id: 'Weapons/Bows/bow-brown-reddish-grip', name: 'Composite Bow' },
            { id: 'Weapons/Bows/bow-fiery-orange-yellow-glow', name: 'Hunter\'s Bow' },
        ],
        daggers: [
            { id: 'Weapons/Throwing Knife/throwing-knife-dagger-beige-blade-brown-handle-wrapped', name: 'Dagger' },
            { id: 'Weapons/Throwing Knife/throwing-knife-beige-blade-brown-handle-pommel', name: 'Dirk' },
            { id: 'Weapons/Throwing Knife/throwing-knife-fire-blade-red-orange-yellow-beige-hilt-crossguard', name: 'Ritual Dagger' },
            { id: 'Weapons/Dart/dart-broom-orange-yellow-bristles-brown-handle', name: 'Assassin\'s Blade' },
        ],
        spears: [
            { id: 'Weapons/Polearm/polearm-spear-staff-brown-wrapped-light-tip', name: 'Simple Spear' },
            { id: 'Weapons/Jousting Spear/jousting-spear-sword-brown-golden-metallic-blade', name: 'War Spear' },
            { id: 'Weapons/Polearm/polearm-halberd-axe-blade-spike-tan-metallic', name: 'Halberd' },
            { id: 'Weapons/Polearm/polearm-halberd-axe-blade-spike-tan-metallic-guard', name: 'Ornate Spear' },
        ],
        wands: [
            { id: 'Weapons/Wand/wand-wooden-staff-brown-tan', name: 'Wooden Wand' },
            { id: 'Weapons/Wand/wand-magical-fire-orange-yellow', name: 'Fire Wand' },
            { id: 'Weapons/Wand/wand-magical-ice-blue-white', name: 'Ice Wand' },
            { id: 'Weapons/Wand/wand-magical-lightning-yellow-blue', name: 'Lightning Wand' },
            { id: 'Weapons/Wand/wand-magical-arcane-purple', name: 'Arcane Wand' },
        ],
        shields: [
            { id: 'Weapons/Shields/shield-heater-wooden-brown-worn-cracks-beige-boss', name: 'Heater Shield' },
            { id: 'Weapons/Shields/shield-round-wooden-brown-metallic-rim-phoenix-eagle-emblem', name: 'Round Shield' },
            { id: 'Weapons/Shields/shield-kite-brown-leather-straps', name: 'Kite Shield' },
            { id: 'Weapons/Shields/shield-tower-metal-bronze', name: 'Tower Shield' },
        ],
        other: [
            { id: 'Weapons/Flail/flail-spiked-ball-chain-brown-handle', name: 'Flail' },
            { id: 'Weapons/Scythe/scythe-curved-blade-brown-handle', name: 'Scythe' },
            { id: 'Weapons/Halberd/halberd-axe-blade-spike', name: 'Halberd' },
            { id: 'Weapons/Chakram/chakram-circular-blade', name: 'Chakram' },
        ],
    },
    armor: {
        plate: [
            { id: 'Armor/Chest/chest-bronze-breastplate', name: 'Plate Chest' },
            { id: 'Armor/Chest/chest-steel-plate-breastplate', name: 'Heavy Plate' },
            { id: 'Armor/Chest/chest-golden-emerald-breastplate', name: 'Ornate Plate' },
            { id: 'Armor/Head/head-brown-tan-banded-helmet', name: 'Plate Helm' },
            { id: 'Armor/Head/head-teal-knight-great-helm', name: 'Full Helm' },
            { id: 'Armor/Feet/feet-tan-beige-boots-pair', name: 'Plate Boots' },
            { id: 'Armor/Feet/feet-animal-paw-boot', name: 'Sabatons' },
            { id: 'Armor/Shoulder/shoulder-pauldron-segmented-brown-tan-cream-layered', name: 'Plate Shoulders' },
            { id: 'Armor/Wrist/worn-leather-bracer', name: 'Plate Bracers' },
            { id: 'Armor/Leggings/leggings-blood-stained-teal-pants', name: 'Plate Leggings' },
            { id: 'Armor/Hands/hands-orange-cream-banded-glove', name: 'Plate Gauntlets' },
            { id: 'Armor/Waist/brown-beaded-necklace-belt', name: 'Plate Belt' },
        ],
        mail: [
            { id: 'Armor/Chest/chest-teal-scale-mail', name: 'Chain Chest' },
            { id: 'Armor/Chest/chest-green-scale-red-accents', name: 'Heavy Chain' },
            { id: 'Armor/Head/head-cross-chainmail-helmet', name: 'Chain Helm' },
            { id: 'Armor/Head/head-cross-chainmail-coif-helmet', name: 'Mail Coif' },
            { id: 'Armor/Feet/feet-tan-beige-boots-pair', name: 'Chain Boots' },
            { id: 'Armor/Feet/feet-animal-paw-boot', name: 'Mail Boots' },
            { id: 'Armor/Shoulder/shoulder-pauldron-segmented-brown-tan-cream-layered', name: 'Mail Shoulders' },
            { id: 'Armor/Wrist/worn-leather-bracer', name: 'Mail Bracers' },
            { id: 'Armor/Leggings/leggings-blood-stained-teal-pants', name: 'Mail Leggings' },
            { id: 'Armor/Hands/hands-orange-cream-banded-glove', name: 'Mail Gloves' },
            { id: 'Armor/Waist/brown-beaded-necklace-belt', name: 'Mail Belt' },
        ],
        leather: [
            { id: 'Armor/Chest/chest-barbarian-leather-tunic', name: 'Leather Chest' },
            { id: 'Armor/Chest/chest-reinforced-leather-cuirass', name: 'Reinforced Leather' },
            { id: 'Armor/Head/head-fur-eared-brown-helmet', name: 'Leather Helm' },
            { id: 'Armor/Head/head-beige-earflap-winter-hat', name: 'Leather Cap' },
            { id: 'Armor/Feet/feet-tan-beige-boots-pair', name: 'Leather Boots' },
            { id: 'Armor/Feet/feet-animal-paw-boot', name: 'Light Boots' },
            { id: 'Armor/Shoulder/shoulder-pauldron-segmented-brown-tan-cream-layered', name: 'Leather Shoulders' },
            { id: 'Armor/Wrist/worn-leather-bracer', name: 'Leather Bracers' },
            { id: 'Armor/Leggings/leggings-blood-stained-teal-pants', name: 'Leather Pants' },
            { id: 'Armor/Hands/hands-orange-cream-banded-glove', name: 'Leather Gloves' },
            { id: 'Armor/Waist/brown-beaded-necklace-belt', name: 'Leather Belt' },
        ],
        cloth: [
            { id: 'Armor/Chest/chest-belted-brown-robe', name: 'Cloth Robe' },
            { id: 'Armor/Chest/chest-flowing-sleeve-tunic', name: 'Embroidered Robe' },
            { id: 'Armor/Head/head-brown-hooded-cloak', name: 'Cloth Hood' },
            { id: 'Armor/Head/head-feathered-brown-wizard-hat', name: 'Wizard Hat' },
            { id: 'Armor/Feet/feet-tan-beige-boots-pair', name: 'Cloth Shoes' },
            { id: 'Armor/Feet/feet-animal-paw-boot', name: 'Silk Slippers' },
            { id: 'Armor/Shoulder/shoulder-pauldron-segmented-brown-tan-cream-layered', name: 'Cloth Shoulders' },
            { id: 'Armor/Wrist/worn-leather-bracer', name: 'Cloth Bracers' },
            { id: 'Armor/Leggings/leggings-blood-stained-teal-pants', name: 'Cloth Pants' },
            { id: 'Armor/Hands/hands-orange-cream-banded-glove', name: 'Cloth Gloves' },
            { id: 'Armor/Waist/brown-beaded-necklace-belt', name: 'Cloth Belt' },
        ],
    },
    cloaks: [
        { id: 'Armor/Cloak/beige-brown-collared-cloak', name: 'Simple Cloak' },
        { id: 'Armor/Cloak/beige-brown-triangular-cloak', name: 'Embroidered Cloak' },
        { id: 'Armor/Cloak/beige-hooded-cloak', name: 'Noble Cloak' },
        { id: 'Armor/Cloak/beige-tan-hooded-cloak', name: 'Magic Cloak' },
        { id: 'Armor/Cloak/cloak-autumn-leaf-trim-cape', name: 'Fur Cloak' },
    ],
    jewelry: {
        rings: [
            { id: 'Armor/Finger/finger-ancient-bronze-ring', name: 'Simple Ring' },
            { id: 'Armor/Finger/finger-brown-braided-ring', name: 'Gold Ring' },
            { id: 'Armor/Finger/finger-bone-claw-red-gem-ring', name: 'Ruby Ring' },
            { id: 'Armor/Finger/finger-brown-stitched-ring', name: 'Signet Ring' },
            { id: 'Armor/Finger/finger-brown-sandals-ring', name: 'Magic Ring' },
        ],
        necklaces: [
            { id: 'Armor/Neck/glowing-orb-pendant', name: 'Amulet' },
            { id: 'Armor/Neck/archery-pendant', name: 'Gold Necklace' },
            { id: 'Armor/Neck/autumn-leaves-pendant', name: 'Pendant' },
            { id: 'Armor/Neck/fiery-orb-amulet', name: 'Gem Necklace' },
        ],
        trinkets: [
            { id: 'Armor/Neck/magical-sword-pendant', name: 'Talisman' },
            { id: 'Armor/Neck/bomb-pendant', name: 'Idol' },
            { id: 'Armor/Neck/glowing-orb-pendant', name: 'Orb' },
            { id: 'Armor/Neck/fiery-orb-amulet', name: 'Charm' },
        ],
    },
    containers: [
        { id: 'Container/Bag/brown-backpack-simple', name: 'Leather Bag' },
        { id: 'Container/Bag/brown-backpack-buckle', name: 'Magic Bag' },
        { id: 'Container/Bag/brown-backpack-flap-straps', name: 'Large Bag' },
        { id: 'Container/Pouch/acorn-pouch', name: 'Small Pouch' },
        { id: 'Container/Bag/adventurer-backpack-gear', name: 'Adventurer\'s Pack' },
        { id: 'Container/Bag/brown-backpack-flap', name: 'Enchanted Bag' },
        { id: 'Container/Chest/wooden-crate-brown-planks-isometric', name: 'Wooden Box' },
        { id: 'Container/Chest/treasure-chest-wooden-brown-straps', name: 'Iron Chest' },
        { id: 'Container/Pouch/brown-red-ribbon-pouch', name: 'Herb Pouch' },
    ],
    consumables: {
        potions: [
            { id: 'Misc/Profession Resources/Alchemy/Red/red-potion-angular-flask-base', name: 'Red Potion' },
            { id: 'Misc/Profession Resources/Alchemy/Blue/blue-potion-bottle-bulbous-base-neck', name: 'Blue Potion' },
            { id: 'Misc/Profession Resources/Alchemy/Orange/orange-potion-arm-flexing-bicep-heart-b-shape-light-beige-pale-orange-vibrant-orange-reddish-orange-sleeve-wristband-brown-shading-highlights', name: 'Orange Potion' },
            { id: 'Misc/Profession Resources/Alchemy/Dark Green/dark-green-potion-bottle', name: 'Green Potion' },
            { id: 'Misc/Profession Resources/Alchemy/Empty/empty-potion-bottle-clear', name: 'Empty Bottle' },
        ],
        food: [
            { id: 'Misc/Profession Resources/Cooking/Food/Other/bread-loaf-rustic-artisan-slashes', name: 'Bread' },
            { id: 'Misc/Profession Resources/Cooking/Food/Other/bread-roll-pastry', name: 'Cheese' },
            { id: 'Misc/Profession Resources/Cooking/Food/Other/bacon-strip-wavy', name: 'Cooked Meat' },
            { id: 'Misc/Profession Resources/Cooking/Food/Other/cake-slice-layered', name: 'Cake' },
            { id: 'Misc/Profession Resources/Cooking/Food/Other/bread-loaf-sliced-blocky', name: 'Sliced Bread' },
        ],
        fruits: [
            { id: 'Misc/Profession Resources/Cooking/Food/Fruit/red-apple', name: 'Red Apple' },
            { id: 'Misc/Profession Resources/Cooking/Food/Fruit/red-apple-leaves', name: 'Apple with Leaves' },
            { id: 'Misc/Profession Resources/Cooking/Food/Fruit/yellow-banana', name: 'Banana' },
            { id: 'Misc/Profession Resources/Cooking/Food/Fruit/orange-peach', name: 'Peach' },
            { id: 'Misc/Profession Resources/Cooking/Food/Fruit/red-strawberry', name: 'Strawberry' },
            { id: 'Misc/Profession Resources/Cooking/Food/Fruit/golden-grape-bunch', name: 'Grapes' },
            { id: 'Misc/Profession Resources/Cooking/Food/Fruit/pineapple-crown', name: 'Pineapple' },
            { id: 'Misc/Profession Resources/Cooking/Food/Fruit/avocado-half', name: 'Avocado' },
            { id: 'Misc/Profession Resources/Cooking/Food/Fruit/kiwi-slice', name: 'Kiwi' },
            { id: 'Misc/Profession Resources/Cooking/Food/Fruit/green-watermelon', name: 'Watermelon' },
            { id: 'Misc/Profession Resources/Cooking/Food/Fruit/yellow-lemon-charm', name: 'Lemon' },
            { id: 'Misc/Profession Resources/Cooking/Food/Fruit/red-chili-pepper', name: 'Chili Pepper' },
        ],
        vegetables: [
            { id: 'Food/Vegetables/carrot-orange-green-stem', name: 'Carrot' },
            { id: 'Food/Vegetables/tomato-red-green-stem', name: 'Tomato' },
            { id: 'Food/Vegetables/potato-brown-oval-eyes', name: 'Potato' },
            { id: 'Food/Vegetables/corn-ear-yellow-husk-green', name: 'Corn' },
            { id: 'Food/Vegetables/pumpkin-orange-stem-leaves-ridged', name: 'Pumpkin' },
            { id: 'Food/Vegetables/eggplant-purple-glossy-stem', name: 'Eggplant' },
            { id: 'Food/Vegetables/cucumber-pickle-green-yellow-blossom', name: 'Cucumber' },
            { id: 'Food/Vegetables/bell-pepper-orange-yellow-green-stem', name: 'Bell Pepper' },
            { id: 'Food/Vegetables/mushroom-red-white-spots', name: 'Red Mushroom' },
            { id: 'Food/Vegetables/mushroom-brown-cap-beige-stem-gills', name: 'Brown Mushroom' },
        ],
        scrolls: [
            { id: 'Misc/Books/book-scroll-rolled-red-wax-seal', name: 'Spell Scroll' },
            { id: 'Misc/Books/book-scroll-parchment-rolled', name: 'Magic Scroll' },
            { id: 'Misc/Books/book-scroll-partially-unrolled-rods', name: 'Ancient Scroll' },
            { id: 'Misc/Books/book-scroll-teal-compass-runes-number', name: 'Enchanted Scroll' },
        ],
    },
    quest: [
        { id: 'Misc/Books/book-scroll-parchment-rolled', name: 'Scroll' },
        { id: 'Misc/Books/book-banner-v-symbol-wooden-rods', name: 'Book' },
        { id: 'Misc/Books/book-blank-sheet-paper-shadow', name: 'Key' },
        { id: 'Misc/Books/book-brown-alchemy-flask-symbol', name: 'Golden Key' },
        { id: 'Misc/Books/book-banner-v-symbol-wooden-rods', name: 'Tome' },
        { id: 'Misc/Books/book-banner-v-symbol-wooden-rods', name: 'Spellbook' },
        { id: 'Misc/Books/book-blank-sheet-paper-shadow', name: 'Quest Item' },
        { id: 'Misc/Books/book-brown-fire-symbol-runes', name: 'Rune' },
        { id: 'Misc/Books/book-brown-red-emblem-clasp', name: 'Gem' },
    ],
    misc: [
        { id: 'Container/Coins/golden-coin-single-isometric', name: 'Coin' },
        { id: 'Misc/Books/book-brown-red-emblem-clasp', name: 'Gemstone' },
        { id: 'Misc/Books/book-brown-alchemy-flask-symbol', name: 'Horn' },
        { id: 'Misc/Books/book-blank-sheet-paper-shadow', name: 'Lantern' },
        { id: 'Misc/Books/book-brown-fire-symbol-runes', name: 'Torch' },
        { id: 'Misc/Books/book-scroll-parchment-rolled', name: 'Rope' },
        { id: 'Misc/Books/book-blank-sheet-paper-shadow', name: 'Lockpicks' },
    ],
    tools: [
        { id: 'Tools/pickaxe', name: 'Pickaxe' },
        { id: 'Tools/shovel', name: 'Shovel' },
        { id: 'Tools/hand-saw', name: 'Hand Saw' },
        { id: 'Tools/chisel', name: 'Chisel' },
        { id: 'Tools/claw-hammer', name: 'Hammer' },
        { id: 'Tools/sledgehammer', name: 'Sledgehammer' },
        { id: 'Tools/scissors-brown-tan-handles', name: 'Scissors' },
        { id: 'Tools/mortar-pestle-beige-reddish-brown', name: 'Mortar & Pestle' },
        { id: 'Tools/sickle-brown-curved-blade', name: 'Sickle' },
        { id: 'Tools/pliers-tongs', name: 'Pliers' },
        { id: 'Tools/dropper-pipette', name: 'Dropper' },
        { id: 'Tools/hand-plane', name: 'Hand Plane' },
        { id: 'Tools/stone-axe', name: 'Stone Axe' },
        { id: 'Tools/small-blade-knife', name: 'Small Blade' },
    ],
    instruments: [
        { id: 'Instruments/Drum/drum-wooden-cylindrical-banded', name: 'Drum' },
        { id: 'Instruments/Flute/flute-reddish-brown-wooden-bands', name: 'Flute' },
        { id: 'Instruments/Harp/harp-brown-beige-strings', name: 'Harp' },
        { id: 'Instruments/Lute/lute-pear-shaped-reddish-brown', name: 'Lute' },
        { id: 'Instruments/Violin/violin-brown-f-holes-bow', name: 'Violin' },
        { id: 'Instruments/Trumpet/trumpet-bugle-brass-golden', name: 'Trumpet' },
        { id: 'Instruments/Horn/horn-curved-segmented', name: 'Horn' },
        { id: 'Instruments/Guitar/guitar-ukulele-warm-brown', name: 'Guitar' },
        { id: 'Instruments/Pan Flute/pan-flute-wooden-bundle', name: 'Pan Flute' },
    ],
    fishing: [
        { id: 'Fishing/Fishing Pole/fishing-pole-simple-brown-line', name: 'Fishing Rod' },
        { id: 'Fishing/curved-hook-boomerang', name: 'Fish Hook' },
        { id: 'Fishing/fishing-net-scoop', name: 'Fishing Net' },
        { id: 'Fishing/fishing-bait-worms', name: 'Bait' },
        { id: 'Fishing/trout-salmon-spotted-arc', name: 'Trout' },
        { id: 'Fishing/bass-trout-olive-green', name: 'Bass' },
    ],
    nature: [
        { id: 'Nature/tree-branch-green-leaves', name: 'Tree Branch' },
        { id: 'Nature/red-rose-orange-petals', name: 'Rose' },
        { id: 'Nature/autumn-maple-leaf', name: 'Maple Leaf' },
        { id: 'Nature/mushroom-red-cap-beige-stem', name: 'Red Mushroom' },
        { id: 'Nature/mushroom-brown-cap-cream-stem', name: 'Brown Mushroom' },
        { id: 'Nature/sunflower-golden-petals-brown-center', name: 'Sunflower' },
        { id: 'Nature/four-leaf-clover-lucky', name: 'Four Leaf Clover' },
        { id: 'Nature/corn-ear-golden-husk', name: 'Corn' },
    ],
};

// Base URL for WoW icons (legacy - not used for items)
export const WOW_ICON_BASE_URL = 'https://wow.zamimg.com/images/wow/icons/large/';

// Import the correct getIconUrl from assetManager
import { getIconUrl as getAssetIconUrl } from '../../utils/assetManager';

// Function to get full icon URL - uses only local assets for items
export const getIconUrl = (iconId, category = 'items') => {
    if (!iconId) {
        // Use a local fallback icon instead of WoW icon
        return getAssetIconUrl('Misc/Books/book-brown-teal-question-mark', category);
    }
    // For items, always use local assets only - no WoW fallback
    return getAssetIconUrl(iconId, category);
};
