// List of WoW Classic icons categorized by type
export const WOW_ICONS = {
    weapons: {
        swords: [
            { id: 'inv_sword_04', name: 'Basic Sword' },
            { id: 'inv_sword_23', name: 'Ornate Sword' },
            { id: 'inv_sword_34', name: 'Bastard Sword' },
            { id: 'inv_sword_39', name: 'Curved Blade' },
            { id: 'inv_sword_27', name: 'Broadsword' },
            { id: 'inv_sword_31', name: 'Rapier' },
            { id: 'inv_sword_15', name: 'Longsword' },
        ],
        axes: [
            { id: 'inv_axe_01', name: 'Battle Axe' },
            { id: 'inv_axe_09', name: 'Double Axe' },
            { id: 'inv_axe_17', name: 'War Axe' },
            { id: 'inv_throwingaxe_01', name: 'Throwing Axe' },
            { id: 'inv_axe_11', name: 'Heavy Axe' },
            { id: 'inv_axe_22', name: 'Ceremonial Axe' },
        ],
        maces: [
            { id: 'inv_mace_01', name: 'Simple Mace' },
            { id: 'inv_mace_06', name: 'Spiked Mace' },
            { id: 'inv_hammer_16', name: 'War Hammer' },
            { id: 'inv_mace_13', name: 'Flanged Mace' },
            { id: 'inv_hammer_20', name: 'Maul' },
            { id: 'inv_mace_21', name: 'Ornate Mace' },
        ],
        staves: [
            { id: 'inv_staff_07', name: 'Wooden Staff' },
            { id: 'inv_staff_20', name: 'Magic Staff' },
            { id: 'inv_staff_31', name: 'Crystal Staff' },
            { id: 'inv_staff_14', name: 'Gnarled Staff' },
            { id: 'inv_staff_51', name: 'Ceremonial Staff' },
            { id: 'inv_staff_40', name: 'Runed Staff' },
        ],
        bows: [
            { id: 'inv_weapon_bow_07', name: 'Recurve Bow' },
            { id: 'inv_weapon_bow_02', name: 'Long Bow' },
            { id: 'inv_weapon_bow_11', name: 'Elven Bow' },
            { id: 'inv_weapon_crossbow_02', name: 'Crossbow' },
            { id: 'inv_weapon_bow_05', name: 'Composite Bow' },
            { id: 'inv_weapon_bow_08', name: 'Hunter\'s Bow' },
        ],
        daggers: [
            { id: 'inv_weapon_shortblade_01', name: 'Dagger' },
            { id: 'inv_weapon_shortblade_05', name: 'Dirk' },
            { id: 'inv_weapon_shortblade_15', name: 'Ritual Dagger' },
            { id: 'inv_weapon_shortblade_21', name: 'Assassin\'s Blade' },
        ],
        spears: [
            { id: 'inv_spear_01', name: 'Simple Spear' },
            { id: 'inv_spear_06', name: 'War Spear' },
            { id: 'inv_spear_08', name: 'Halberd' },
            { id: 'inv_spear_03', name: 'Ornate Spear' },
        ],
    },
    armor: {
        plate: [
            { id: 'inv_chest_plate04', name: 'Plate Chest' },
            { id: 'inv_chest_plate03', name: 'Heavy Plate' },
            { id: 'inv_chest_plate02', name: 'Ornate Plate' },
            { id: 'inv_helmet_05', name: 'Plate Helm' },
            { id: 'inv_helmet_10', name: 'Full Helm' },
            { id: 'inv_boots_plate_01', name: 'Plate Boots' },
            { id: 'inv_boots_plate_04', name: 'Sabatons' },
            { id: 'inv_shoulder_11', name: 'Plate Shoulders' },
            { id: 'inv_bracer_19', name: 'Plate Bracers' },
            { id: 'inv_pants_plate_12', name: 'Plate Leggings' },
            { id: 'inv_gauntlets_29', name: 'Plate Gauntlets' },
            { id: 'inv_belt_13', name: 'Plate Belt' },
        ],
        mail: [
            { id: 'inv_chest_chain', name: 'Chain Chest' },
            { id: 'inv_chest_chain_05', name: 'Heavy Chain' },
            { id: 'inv_helmet_03', name: 'Chain Helm' },
            { id: 'inv_helmet_08', name: 'Mail Coif' },
            { id: 'inv_boots_chain_02', name: 'Chain Boots' },
            { id: 'inv_boots_chain_05', name: 'Mail Boots' },
            { id: 'inv_shoulder_01', name: 'Mail Shoulders' },
            { id: 'inv_bracer_03', name: 'Mail Bracers' },
            { id: 'inv_pants_mail_15', name: 'Mail Leggings' },
            { id: 'inv_gauntlets_11', name: 'Mail Gloves' },
            { id: 'inv_belt_16', name: 'Mail Belt' },
        ],
        leather: [
            { id: 'inv_chest_leather_01', name: 'Leather Chest' },
            { id: 'inv_chest_leather_08', name: 'Reinforced Leather' },
            { id: 'inv_helmet_09', name: 'Leather Helm' },
            { id: 'inv_helmet_45', name: 'Leather Cap' },
            { id: 'inv_boots_08', name: 'Leather Boots' },
            { id: 'inv_boots_07', name: 'Light Boots' },
            { id: 'inv_shoulder_08', name: 'Leather Shoulders' },
            { id: 'inv_bracer_07', name: 'Leather Bracers' },
            { id: 'inv_pants_leather_20', name: 'Leather Pants' },
            { id: 'inv_gauntlets_21', name: 'Leather Gloves' },
            { id: 'inv_belt_24', name: 'Leather Belt' },
        ],
        cloth: [
            { id: 'inv_chest_cloth_01', name: 'Cloth Robe' },
            { id: 'inv_chest_cloth_23', name: 'Embroidered Robe' },
            { id: 'inv_helmet_30', name: 'Cloth Hood' },
            { id: 'inv_helmet_31', name: 'Wizard Hat' },
            { id: 'inv_boots_cloth_01', name: 'Cloth Shoes' },
            { id: 'inv_boots_cloth_05', name: 'Silk Slippers' },
            { id: 'inv_shoulder_02', name: 'Cloth Shoulders' },
            { id: 'inv_bracer_02', name: 'Cloth Bracers' },
            { id: 'inv_pants_cloth_14', name: 'Cloth Pants' },
            { id: 'inv_gauntlets_27', name: 'Cloth Gloves' },
            { id: 'inv_belt_04', name: 'Cloth Belt' },
        ],
    },
    cloaks: [
        { id: 'inv_misc_cape_01', name: 'Simple Cloak' },
        { id: 'inv_misc_cape_02', name: 'Embroidered Cloak' },
        { id: 'inv_misc_cape_18', name: 'Noble Cloak' },
        { id: 'inv_misc_cape_20', name: 'Magic Cloak' },
        { id: 'inv_misc_cape_11', name: 'Fur Cloak' },
    ],
    jewelry: {
        rings: [
            { id: 'inv_jewelry_ring_01', name: 'Simple Ring' },
            { id: 'inv_jewelry_ring_03', name: 'Gold Ring' },
            { id: 'inv_jewelry_ring_05', name: 'Ruby Ring' },
            { id: 'inv_jewelry_ring_27', name: 'Signet Ring' },
            { id: 'inv_jewelry_ring_23', name: 'Magic Ring' },
        ],
        necklaces: [
            { id: 'inv_jewelry_necklace_01', name: 'Amulet' },
            { id: 'inv_jewelry_necklace_07', name: 'Gold Necklace' },
            { id: 'inv_jewelry_necklace_13', name: 'Pendant' },
            { id: 'inv_jewelry_necklace_21', name: 'Gem Necklace' },
        ],
        trinkets: [
            { id: 'inv_jewelry_talisman_01', name: 'Talisman' },
            { id: 'inv_misc_idol_02', name: 'Idol' },
            { id: 'inv_misc_orb_01', name: 'Orb' },
            { id: 'inv_jewelry_trinket_01', name: 'Charm' },
        ],
    },
    containers: [
        { id: 'inv_misc_bag_07', name: 'Leather Bag' },
        { id: 'inv_misc_bag_10_blue', name: 'Magic Bag' },
        { id: 'inv_misc_bag_11', name: 'Large Bag' },
        { id: 'inv_misc_bag_08', name: 'Small Pouch' },
        { id: 'inv_misc_bag_19', name: 'Adventurer\'s Pack' },
        { id: 'inv_misc_bag_23', name: 'Enchanted Bag' },
        { id: 'inv_box_01', name: 'Wooden Box' },
        { id: 'inv_box_03', name: 'Iron Chest' },
        { id: 'inv_misc_bag_cenarionherbbag', name: 'Herb Pouch' },
    ],
    consumables: {
        potions: [
            { id: 'inv_potion_51', name: 'Red Potion' },
            { id: 'inv_potion_52', name: 'Blue Potion' },
            { id: 'inv_potion_54', name: 'Purple Potion' },
            { id: 'inv_potion_35', name: 'Green Potion' },
            { id: 'inv_potion_21', name: 'Yellow Potion' },
            { id: 'inv_potion_162', name: 'Black Potion' },
        ],
        food: [
            { id: 'inv_misc_food_15', name: 'Bread' },
            { id: 'inv_misc_food_23', name: 'Fruit' },
            { id: 'inv_misc_food_14', name: 'Cheese' },
            { id: 'inv_misc_food_60', name: 'Cooked Meat' },
            { id: 'inv_drink_07', name: 'Wine' },
            { id: 'inv_drink_11', name: 'Water' },
        ],
        scrolls: [
            { id: 'inv_scroll_02', name: 'Spell Scroll' },
            { id: 'inv_scroll_03', name: 'Magic Scroll' },
            { id: 'inv_scroll_06', name: 'Ancient Scroll' },
            { id: 'inv_scroll_11', name: 'Enchanted Scroll' },
        ],
    },
    quest: [
        { id: 'inv_misc_note_01', name: 'Scroll' },
        { id: 'inv_misc_book_08', name: 'Book' },
        { id: 'inv_misc_key_01', name: 'Key' },
        { id: 'inv_misc_key_10', name: 'Golden Key' },
        { id: 'inv_misc_book_02', name: 'Tome' },
        { id: 'inv_misc_book_09', name: 'Spellbook' },
        { id: 'inv_misc_questionmark', name: 'Quest Item' },
        { id: 'inv_misc_rune_01', name: 'Rune' },
        { id: 'inv_misc_gem_01', name: 'Gem' },
    ],
    misc: [
        { id: 'inv_misc_coin_01', name: 'Coin' },
        { id: 'inv_misc_gem_variety_01', name: 'Gemstone' },
        { id: 'inv_misc_horn_01', name: 'Horn' },
        { id: 'inv_misc_lantern_01', name: 'Lantern' },
        { id: 'inv_torch_lit', name: 'Torch' },
        { id: 'inv_misc_rope_01', name: 'Rope' },
        { id: 'inv_misc_lockpick_01', name: 'Lockpicks' },
    ],
};

// Base URL for WoW icons
export const WOW_ICON_BASE_URL = 'https://wow.zamimg.com/images/wow/icons/large/';

// Function to get full icon URL
export const getIconUrl = (iconId) => `${WOW_ICON_BASE_URL}${iconId}.jpg`;
