const fs = require('fs');
const content = fs.readFileSync('server.js', 'utf8');
const lines = content.split('\n');

// Find and replace the problematic block
const oldBlockPattern = /          \/\/ CRITICAL FIX: Don\\'t call createRoom\\(\\) - it generates a new UUID\\n.*?\/\/ Instead, create room object directly with Firestore document ID and normalized data\\n.*?const passwordHash = await hashPassword\\(data\.password \\|\\'\\);\\n.*?room = \\{\\n.*?id: data\.persistentRoomId,.*?\/\/ Use Firestore document ID directly\\n.*?\.\.\.persistedRuntimeRoom,.*?\/\/ Spread all normalized room data\\(gameState, settings, chatHistory, etc\.\\)\\n.*?name: persistedRoomData\.roomName \\|\\| data\.roomName,\\n.*?passwordHash: passwordHash,\\n.*?gm: \\{\\n.*?id: data\.gmName \\|\\| 'GM',\\n.*?name: data\.gmName \\|\\| 'Game Master',\\n.*?socketId: socket\.id,\\n.*?isGM: true,\\n.*?color: data\.playerColor \\|\\| '#d4af37'\\n.*?\\},\\n.*?players: new Map\\(\\),\\n.*?gridSettings: \\{\\n[^}]+\\n\\}/gs;

const newBlock = '          // CRITICAL FIX: Set gm.id from persistedRuntimeRoom BEFORE spread to preserve Firestore document ID\n          // If we use spread first, then assign gm.id separately, it will override the Firestore ID\n          room = {\n            ...persistedRuntimeRoom, // Spread all normalized room data first (includes gm.id from Firestore)\n            id: data.persistentRoomId, // Then set room.id to Firestore document ID\n            name: persistedRoomData.roomName || data.roomName,\n            passwordHash: passwordHash,\n            gm: {\n              // id is now correctly set from persistedRuntimeRoom, not overridden by data.gmName\n              name: data.gmName || \'Game Master\',\n              socketId: socket.id,\n              isGM: true,\n              color: data.playerColor || \'#d4af37\'\n            },\n            players: new Map(),\n            gridSettings: {\n              gridType: \'square\',\n              gridSize: 50,\n              gridOffsetX: 0,\n              gridOffsetY: 0,\n              gridLineColor: \'#000000\',\n              gridLineThickness: 1,\n              gridLineOpacity: 0.5,\n              gridBackgroundColor: \'#d4c5b9\'\n            },\n            lastActivity: new Date().toISOString(),\n            isActive: true,\n            isPermanent: true,\n            persistentRoomId: data.persistentRoomId\n          };\n          \n          // Ensure room has default gameState structure (maps, defaultMapId, etc.)\n          ensureRoomGameStateDefaults(room);\n          \n          logger.info(`[create_room] Room object created from normalized data`, {\n            roomId: room.id,\n            gameStateMapCount: Object.keys(room.gameState?.maps || {}).length,\n            defaultMapId: room.gameState?.defaultMapId,\n            defaultMapHasGridItems: !!room.gameState?.maps?.default?.gridItems,\n            defaultMapGridItemsCount: Object.keys(room.gameState?.maps?.default?.gridItems || {}).length,\n            defaultMapTerrainCount: Object.keys(room.gameState?.maps?.default?.terrainData || {}).length\n          });\n';

const newContent = content.replace(oldBlockPattern, newBlock);
fs.writeFileSync('server.js', newContent, 'utf8');
console.log('Fix applied successfully');
